// Key tables extracted from PTerm 6.0.4 ptermkeytabs.h (generated by composed.py).
// Copyright (c) 2005-2018 Paul Koning et al.  See pterm/pterm-license.txt.
#ifndef PLATO_KEYTABS_H
#define PLATO_KEYTABS_H
#include "compat.h"
static const u32 asciiToPlato[128] = {
   None, KEY (0022, None, None, None),
   KEY (0030, None, None, None), KEY (0033, None, None, None),
   KEY (0031, None, None, None), KEY (0027, None, None, None),
   KEY (0064, None, None, None), KEY (0013, None, None, None),
   KEY (0025, None, None, None), None,
   None, None,
   KEY (0035, None, None, None), KEY (0024, None, None, None),
   KEY (0026, None, None, None), None,
   KEY (0020, None, None, None), KEY (0034, None, None, None),
   KEY (0023, None, None, None), KEY (0032, None, None, None),
   KEY (0062, None, None, None), None,
   None, None,
   KEY (0012, None, None, None), KEY (0021, None, None, None),
   None, None,
   None, None,
   None, None,
   None, KEY (0176, None, None, None),
   KEY (0177, None, None, None), KEY (0074, 0044, None, None),
   KEY (0044, None, None, None), KEY (0045, None, None, None),
   KEY (0074, 0016, None, None), KEY (0047, None, None, None),
   KEY (0051, None, None, None), KEY (0173, None, None, None),
   KEY (0050, None, None, None), KEY (0016, None, None, None),
   KEY (0137, None, None, None), KEY (0017, None, None, None),
   KEY (0136, None, None, None), KEY (0135, None, None, None),
   KEY (0000, None, None, None), KEY (0001, None, None, None),
   KEY (0002, None, None, None), KEY (0003, None, None, None),
   KEY (0004, None, None, None), KEY (0005, None, None, None),
   KEY (0006, None, None, None), KEY (0007, None, None, None),
   KEY (0010, None, None, None), KEY (0011, None, None, None),
   KEY (0174, None, None, None), KEY (0134, None, None, None),
   KEY (0040, None, None, None), KEY (0133, None, None, None),
   KEY (0041, None, None, None), KEY (0175, None, None, None),
   KEY (0074, 0005, None, None), KEY (0141, None, None, None),
   KEY (0142, None, None, None), KEY (0143, None, None, None),
   KEY (0144, None, None, None), KEY (0145, None, None, None),
   KEY (0146, None, None, None), KEY (0147, None, None, None),
   KEY (0150, None, None, None), KEY (0151, None, None, None),
   KEY (0152, None, None, None), KEY (0153, None, None, None),
   KEY (0154, None, None, None), KEY (0155, None, None, None),
   KEY (0156, None, None, None), KEY (0157, None, None, None),
   KEY (0160, None, None, None), KEY (0161, None, None, None),
   KEY (0162, None, None, None), KEY (0163, None, None, None),
   KEY (0164, None, None, None), KEY (0165, None, None, None),
   KEY (0166, None, None, None), KEY (0167, None, None, None),
   KEY (0170, None, None, None), KEY (0171, None, None, None),
   KEY (0172, None, None, None), KEY (0042, None, None, None),
   KEY (0074, 0135, None, None), KEY (0043, None, None, None),
   KEY (0100, 0074, 0130, None), KEY (0046, None, None, None),
   KEY (0100, 0074, 0121, None), KEY (0101, None, None, None),
   KEY (0102, None, None, None), KEY (0103, None, None, None),
   KEY (0104, None, None, None), KEY (0105, None, None, None),
   KEY (0106, None, None, None), KEY (0107, None, None, None),
   KEY (0110, None, None, None), KEY (0111, None, None, None),
   KEY (0112, None, None, None), KEY (0113, None, None, None),
   KEY (0114, None, None, None), KEY (0115, None, None, None),
   KEY (0116, None, None, None), KEY (0117, None, None, None),
   KEY (0120, None, None, None), KEY (0121, None, None, None),
   KEY (0122, None, None, None), KEY (0123, None, None, None),
   KEY (0124, None, None, None), KEY (0125, None, None, None),
   KEY (0126, None, None, None), KEY (0127, None, None, None),
   KEY (0130, None, None, None), KEY (0131, None, None, None),
   KEY (0132, None, None, None), KEY (0074, 0042, None, None),
   KEY (0074, 0151, None, None), KEY (0074, 0043, None, None),
   KEY (0100, 0074, 0116, None), None
};

static const u16 mtutorcvt[128] = {
     60,  26,  24,  27,  17,  49,   6,  18,     // 0 - 7
     19,  53,  12,  21,  29,  22,  56,  61,     // 7 - 15
     16,  58,  25,  16,  50,  21,  59,  48,     // 16 - 23
     55,  51,  23,  27,  28,  57,  54,  96,     // 24 - 31

     64, 126, 127,  46,  36,  37,  10,  43,     // 32 - 39
     41, 123,  40,  14,  95,  15,  94,  93,     // 40 - 47
      0,   1,   2,   3,   4,   5,   6,   7,     // 48 - 55
      8,   9, 124,  92,  32,  91,  33, 125,     // 56 - 63

     42,  97,  98,  99, 100, 101, 102, 103,     // 64 - 71
    104, 105, 106, 107, 108, 109, 110, 111,     // 72 - 79
    112, 113, 114, 115, 116, 117, 118, 119,     // 80 - 87
    120, 121, 122,  34,  45,  35,  13,  38,     // 88 - 95

     11,  65,  66,  67,  68,  69,  70,  71,     // 96 - 103
     72,  73,  74,  75,  76,  77,  78,  79,     // 104 - 111
     80,  81,  82,  83,  84,  85,  86,  87,     // 112 - 119
     88,  89,  90,  20,  39,  28,  47,  52      // 120 - 127

};

/* end of file */
#endif
